#pragma once

namespace giygas {

    enum class InputKey {
        UNKNOWN = 0,

        KEYBOARD_BACKSPACE = 8,
        KEYBOARD_ENTER = 10,
        KEYBOARD_HOME = 13,
        KEYBOARD_ESCAPE = 27,
        KEYBOARD_SPACE = 32,
        KEYBOARD_APOSTROPHE = 39,
        KEYBOARD_COMMA = 44,
        KEYBOARD_HYPHEN = 45,
        KEYBOARD_PERIOD = 46,
        KEYBOARD_FORWARDSLASH = 47,
        KEYBOARD_ZERO = 48,
        KEYBOARD_ONE = 49,
        KEYBOARD_TWO = 50,
        KEYBOARD_THREE = 51,
        KEYBOARD_FOUR = 52,
        KEYBOARD_FIVE = 53,
        KEYBOARD_SIX = 54,
        KEYBOARD_SEVEN = 55,
        KEYBOARD_EIGHT = 56,
        KEYBOARD_NINE = 57,
        KEYBOARD_SEMICOLON = 59,
        KEYBOARD_EQUALS = 61,
        KEYBOARD_A = 65,
        KEYBOARD_B = 66,
        KEYBOARD_C = 67,
        KEYBOARD_D = 68,
        KEYBOARD_E = 69,
        KEYBOARD_F = 70,
        KEYBOARD_G = 71,
        KEYBOARD_H = 72,
        KEYBOARD_I = 73,
        KEYBOARD_J = 74,
        KEYBOARD_K = 75,
        KEYBOARD_L = 76,
        KEYBOARD_M = 77,
        KEYBOARD_N = 78,
        KEYBOARD_O = 79,
        KEYBOARD_P = 80,
        KEYBOARD_Q = 81,
        KEYBOARD_R = 82,
        KEYBOARD_S = 83,
        KEYBOARD_T = 84,
        KEYBOARD_U = 85,
        KEYBOARD_V = 86,
        KEYBOARD_W = 87,
        KEYBOARD_X = 88,
        KEYBOARD_Y = 89,
        KEYBOARD_Z = 90,
        KEYBOARD_LEFT_SQUARE_BRACKET = 91,
        KEYBOARD_BACKSLASH = 92,
        KEYBOARD_RIGHT_SQUARE_BRACKET = 93,
        KEYBOARD_GRAVE_ACCENT = 96,
        KEYBOARD_DELETE = 127,

        KEYBOARD_LEFT = 128,
        KEYBOARD_RIGHT = 129,
        KEYBOARD_UP = 130,
        KEYBOARD_DOWN = 131
    };

}